wandb_version: 1

learning_rate:
  desc: null
  value: 0.0003
epochs:
  desc: null
  value: 50
batch_size:
  desc: null
  value: 32
model:
  desc: null
  value: Deep4SNet
optimizer:
  desc: null
  value: AdamW
weight_decay:
  desc: null
  value: 0.01
scheduler:
  desc: null
  value: CosineAnnealingWarmRestarts
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.15.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1746993961.257198
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.11.5
      5: 0.15.5
      8:
      - 3
      - 8
